version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=4000
      - HOST=db
      - DBPORT=3306
      - DATABASE=cies_rest
      - DBUSER=cies_user
      - PASSWORD=cies_user
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cies_user
      MYSQL_DATABASE: cies_rest
      MYSQL_USER: cies_user
      MYSQL_PASSWORD: cies_user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=cies_user

volumes:
  db_data:
